---
- name: Instalação do DHCP Server e Apache
  hosts: all
  become: true

  roles:
    - role: dhcpd
      when: inventory_hostname == 'dhcp'
    - role: httpd
      when: inventory_hostname == 'apache' 
